[run]
init_cmds = [
	#["grep", "-rn", "FIXME", "."],
	["./gogs", "web"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR/cmd",
	"$WORKDIR/models",
	"$WORKDIR/modules",
	"$WORKDIR/routers"
]
watch_exts = [".go"]
build_delay = 1500
cmds = [
	["go", "install", "-tags", "sqlite"],# redis memcache cert pam tidb
	["go", "build", "-tags", "sqlite"],
	["./gogs", "web"]
]